# Generated by Django 6.0 on 2025-12-16 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='授業名')),
                ('instructor', models.CharField(max_length=100, verbose_name='担当教員')),
                ('description', models.TextField(blank=True, default='', verbose_name='詳細')),
            ],
            options={
                'verbose_name': '授業',
                'verbose_name_plural': '授業',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='曜日名')),
                ('sort_order', models.IntegerField(unique=True, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '曜日',
                'verbose_name_plural': '曜日',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='時限名')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
            ],
            options={
                'verbose_name': '時限',
                'verbose_name_plural': '時限',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限日')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedule.course')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='教室名')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course', verbose_name='授業')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.day', verbose_name='曜日')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.period', verbose_name='時限')),
            ],
            options={
                'verbose_name': '時間割',
                'verbose_name_plural': '時間割',
                'unique_together': {('day', 'period', 'room')},
            },
        ),
    ]
