# Generated by Django 6.0 on 2025-12-16 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['order', 'start_time']},
        ),
        migrations.AddField(
            model_name='day',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='period',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='day',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.timetable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.timetable'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('timetable', 'name'), ('timetable', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('timetable', 'name'), ('timetable', 'order')},
        ),
        migrations.RemoveField(
            model_name='day',
            name='sort_order',
        ),
    ]
