# Generated by Django 6.0 on 2025-12-17 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_day_options_alter_period_options_day_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user', 'day', 'period')},
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=100, verbose_name='教室'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='room',
        ),
    ]
