# Generated by Django 6.0 on 2025-12-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_unique_together_course_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('#e2e8f0', '標準（グレー）'), ('#fbcfe8', 'ピンク'), ('#c7d2fe', 'パープル'), ('#bae6fd', 'スカイ'), ('#bbf7d0', 'グリーン'), ('#fef08a', 'イエロー')], default='#e2e8f0', max_length=7),
        ),
    ]
