# Generated by Django 6.0 on 2025-12-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_course_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.CharField(max_length=100, verbose_name='時間割名'),
        ),
    ]
