"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url  # 【追加】データベース自動切り替え用

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 【変更】環境変数があればそれを使い、なければデフォルト（開発用）を使う
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^!y(*n8&4-lk0h3s9ptu)k5cly)_)jk9j$o76$a2ujb+e&uc%g')

# SECURITY WARNING: don't run with debug turned on in production!
# 【変更】Render環境('RENDER')にいる場合はFalse(本番モード)、それ以外はTrue(開発モード)
DEBUG = 'RENDER' not in os.environ

# 【変更】Render上では全てのホストを許可、開発環境ではlocalhost等
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'schedule',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 【追加】静的ファイル配信用（セキュリティの直下に配置）
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 【変更】デフォルトはSQLite。環境変数 DATABASE_URL があればPostgreSQLに上書き
DATABASES = {
    'default': dj_database_url.parse('postgresql://neondb_owner:npg_cFhQrVb41PaT@ep-wild-bird-a1lc7xa2-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require')
}

# Renderなどのクラウド環境用のDB設定を読み込む
db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True
USE_TZ = True

FORMAT_MODULE_PATH = [
    'config.formats',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 【追加】本番環境で静的ファイルを集める場所
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 【追加】WhiteNoiseを使って静的ファイルを圧縮・配信する設定
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGIN_REDIRECT_URL = 'schedule:time_table'  # ログイン後の遷移先
LOGOUT_REDIRECT_URL = 'login'               # ログアウト後の遷移先